# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 93110e380ca9c3ed2087f14f0389dab779b7f908af0f5b13085bdc1cebd4fe871ed17f12e830c68ba132c415741d6b0fd00268a19514526ad3900c1c87a8e757

test:
  secret_key_base: 6622efbfe696648b21c9ef3e04c53738034704f2aa5e69a064013ec86ba4ab8e8417c86238414e52142913848b798d0e91b04f0eeeeec44d2a847e4b1ec15614

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
